DROP TABLE IF EXISTS MSA_ORDER;

CREATE TABLE MSA_ORDER
(
  ORDERID          VARCHAR(50), 
  USERID            VARCHAR(50),
  NAME 				VARCHAR(20),
  PRODUCTID       VARCHAR(50), 
  QUANTITY             INTEGER,
  UNITPRICE         INTEGER,
  TOTALPRICE       INTEGER,
  CREATE_DATE   DATE DEFAULT CURRENT_DATE
);

alter table MSA_ORDER
  add primary key (ORDERID);