

INSERT INTO MSA_CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, PRICE)
VALUES('CATALOG-0001', 'Java', 100, 1500); 
INSERT INTO MSA_CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, PRICE)
VALUES('CATALOG-0002', 'SQL', 100, 900); 
INSERT INTO MSA_CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, PRICE)
VALUES('CATALOG-0003', 'JSP', 100, 1200); 